# see defaults options https://github.com/yakworks/gradle-plugins/tree/master/src/main/resources/configs/defaults.yml
title: Spring security event log
description: Spring security event log grails plugin - Logs spring security login and other events to database.
author: Yak.Works
group: org.grails.plugins

github:
  fullName: yakworks/spring-security-eventlog

team:
  developers: ['basejump: Joshua Burnett', 'snimavat: Sudhir Nimavat']

bintray:
  enabled: true
  # user: ${findAnyProperty("BINTRAY_USER")} //uses System var property
  # key: ${props.findAny("BINTRAY_KEY")} //uses System var property
  pkg:
    repo: grails-plugins
    userOrg: 9ci

maven:
  # repoUrl: http://repo.9ci.com/grails-plugins
  snapshotUrl: http://repo.9ci.com/oss-snapshots

docs:
  enabled: false

releaseNotes:
  file: CHANGELOG.md
